export const PREDEFINED_CATEGORIES = [
  {
    categoryId: 'CAT001',
    code: 'CLINIC_CONSULT',
    name: 'In-Clinic Consultation',
    description: 'Face-to-face consultations with doctors at clinic or hospital',
    displayOrder: 1,
    isActive: true,
    isAvailableOnline: true,
    isPredefined: true,
  },
  {
    categoryId: 'CAT002',
    code: 'PHARMACY',
    name: 'Pharmacy',
    description: 'Purchase of prescribed medicines and pharmaceutical products',
    displayOrder: 2,
    isActive: true,
    isAvailableOnline: true,
    isPredefined: true,
  },
  {
    categoryId: 'CAT003',
    code: 'DIAGNOSTIC',
    name: 'Radiology/ Cardiology',
    description: 'Diagnostic imaging services including X-ray, MRI, CT scan, and ultrasound',
    displayOrder: 3,
    isActive: true,
    isAvailableOnline: true,
    isPredefined: true,
  },
  {
    categoryId: 'CAT004',
    code: 'LABORATORY',
    name: 'Pathology (Lab)',
    description: 'Clinical laboratory tests including blood tests, urine tests, and pathology',
    displayOrder: 4,
    isActive: true,
    isAvailableOnline: true,
    isPredefined: true,
  },
  {
    categoryId: 'CAT005',
    code: 'ONLINE_CONSULT',
    name: 'Online Consultation',
    description: 'Virtual consultations with doctors via video call or chat',
    displayOrder: 5,
    isActive: true,
    isAvailableOnline: true,
    isPredefined: true,
  },
  {
    categoryId: 'CAT006',
    code: 'DENTAL',
    name: 'Dental Services',
    description: 'Dental care including checkups, cleaning, fillings, and oral treatments',
    displayOrder: 6,
    isActive: true,
    isAvailableOnline: true,
    isPredefined: true,
  },
  {
    categoryId: 'CAT007',
    code: 'VISION',
    name: 'Vision Care',
    description: 'Eye care services including eye exams, glasses, and contact lenses',
    displayOrder: 7,
    isActive: true,
    isAvailableOnline: true,
    isPredefined: true,
  },
  {
    categoryId: 'CAT008',
    code: 'WELLNESS',
    name: 'Wellness Programs',
    description: 'Preventive health services including annual health checks, vaccinations, and wellness programs',
    displayOrder: 8,
    isActive: true,
    isAvailableOnline: true,
    isPredefined: true,
  },
];
