export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  TPA_ADMIN = 'TPA_ADMIN',
  TPA_USER = 'TPA_USER',
  FINANCE_ADMIN = 'FINANCE_ADMIN',
  FINANCE_USER = 'FINANCE_USER',
  OPS_ADMIN = 'OPS_ADMIN',
  OPS_USER = 'OPS_USER',
  MEMBER = 'MEMBER',
  DOCTOR = 'DOCTOR',
}