version: '3.8'

services:
  # Nginx Reverse Proxy
  nginx:
    image: 695990114347.dkr.ecr.eu-north-1.amazonaws.com/opdwallet/nginx:latest
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: opd-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - web-admin
      - web-member
    restart: unless-stopped
    networks:
      - opd-network

  # MongoDB Database (using public image)
  mongodb:
    image: mongo:7.0
    container_name: opd-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: opd_wallet
    volumes:
      - mongo-data:/data/db
    networks:
      - opd-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 5

  # NestJS API
  api:
    image: 695990114347.dkr.ecr.eu-north-1.amazonaws.com/opdwallet/api:latest
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    container_name: opd-api
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: 4000
      MONGODB_URI: mongodb://mongodb:27017/opd_wallet
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key-change-in-production}
      COOKIE_NAME: opd_session
      COOKIE_DOMAIN: ${COOKIE_DOMAIN}
      COOKIE_SECURE: ${COOKIE_SECURE:-false}
      COOKIE_HTTPONLY: "true"
      COOKIE_SAMESITE: "lax"
      CORS_ORIGIN: ${CORS_ORIGIN:-*}
    depends_on:
      - mongodb
    networks:
      - opd-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Admin Portal (Next.js)
  web-admin:
    image: 695990114347.dkr.ecr.eu-north-1.amazonaws.com/opdwallet/web-admin:latest
    build:
      context: ./web-admin
      dockerfile: Dockerfile.prod
    container_name: opd-web-admin
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      API_URL: http://api:4000/api
      NEXT_PUBLIC_API_URL: ${PUBLIC_API_URL:-http://13.60.210.156/api}
    depends_on:
      - api
    networks:
      - opd-network

  # Member Portal (Next.js)
  web-member:
    image: 695990114347.dkr.ecr.eu-north-1.amazonaws.com/opdwallet/web-member:latest
    build:
      context: ./web-member
      dockerfile: Dockerfile.prod
    container_name: opd-web-member
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      API_URL: http://api:4000/api
      NEXT_PUBLIC_API_URL: ${PUBLIC_API_URL:-http://13.60.210.156/api}
    depends_on:
      - api
    networks:
      - opd-network

networks:
  opd-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local