import {
  IsString,
  IsBoolean,
  IsOptional,
  IsNotEmpty,
  IsNumber,
  Min,
  IsEnum,
} from 'class-validator';
import { Transform } from 'class-transformer';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { EmployeeCount } from '@/common/constants/status.enum';

export class CreateCugDto {
  // cugId is now auto-generated by the system

  @ApiPropertyOptional({
    description: 'Optional short code for quick reference',
    example: 'GOOGLE',
  })
  @IsOptional()
  @IsString()
  @Transform(({ value }) => value?.toUpperCase())
  shortCode?: string;

  @ApiProperty({
    description: 'Official company name',
    example: 'Google Inc.',
  })
  @IsNotEmpty()
  @IsString()
  companyName: string;

  @ApiProperty({
    description: 'Employee count range',
    enum: EmployeeCount,
    example: EmployeeCount.ONE_THOUSAND_TO_5000,
  })
  @IsNotEmpty()
  @IsEnum(EmployeeCount)
  employeeCount: EmployeeCount;

  @ApiPropertyOptional({
    description: 'CUG description',
    example: 'Google corporate group',
  })
  @IsOptional()
  @IsString()
  description?: string;

  @ApiPropertyOptional({
    description: 'Whether the CUG is active',
    default: true,
  })
  @IsOptional()
  @IsBoolean()
  isActive?: boolean = true;

  @ApiPropertyOptional({
    description: 'Display order for sorting',
    default: 0,
    minimum: 0,
  })
  @IsOptional()
  @IsNumber()
  @Min(0)
  displayOrder?: number = 0;
}

export class UpdateCugDto {
  @ApiPropertyOptional({
    description: 'Optional short code for quick reference',
    example: 'GOOGLE',
  })
  @IsOptional()
  @IsString()
  @Transform(({ value }) => value?.toUpperCase())
  shortCode?: string;

  @ApiPropertyOptional({
    description: 'Official company name',
    example: 'Google Inc.',
  })
  @IsOptional()
  @IsString()
  companyName?: string;

  @ApiPropertyOptional({
    description: 'Employee count range',
    enum: EmployeeCount,
  })
  @IsOptional()
  @IsEnum(EmployeeCount)
  employeeCount?: EmployeeCount;

  @ApiPropertyOptional({
    description: 'CUG description',
    example: 'Google corporate group',
  })
  @IsOptional()
  @IsString()
  description?: string;

  @ApiPropertyOptional({
    description: 'Whether the CUG is active',
  })
  @IsOptional()
  @IsBoolean()
  isActive?: boolean;

  @ApiPropertyOptional({
    description: 'Display order for sorting',
    minimum: 0,
  })
  @IsOptional()
  @IsNumber()
  @Min(0)
  displayOrder?: number;
}