export const PREDEFINED_CATEGORIES = [
  {
    id: 'CAT001',
    name: 'In-Clinic',
    fullName: 'In-Clinic Consultation',
    hasSpecialties: true,
    hasLabServices: false,
    hasServiceManagement: false,
  },
  {
    id: 'CAT002',
    name: 'Pharmacy',
    fullName: 'Pharmacy',
    hasSpecialties: false,
    hasLabServices: false,
    hasServiceManagement: false,
  },
  {
    id: 'CAT003',
    name: 'Diagnostic',
    fullName: 'Diagnostic Services',
    hasSpecialties: false,
    hasLabServices: true,
    labServiceCategories: ['RADIOLOGY', 'ENDOSCOPY'],
    hasServiceManagement: false,
  },
  {
    id: 'CAT004',
    name: 'Laboratory',
    fullName: 'Laboratory Services',
    hasSpecialties: false,
    hasLabServices: true,
    labServiceCategories: ['PATHOLOGY', 'CARDIOLOGY', 'OTHER'],
    hasServiceManagement: false,
  },
  {
    id: 'CAT005',
    name: 'Online',
    fullName: 'Online Consultation',
    hasSpecialties: true,
    hasLabServices: false,
    hasServiceManagement: false,
  },
  {
    id: 'CAT006',
    name: 'Dental',
    fullName: 'Dental Services',
    hasSpecialties: false,
    hasLabServices: false,
    hasServiceManagement: true,
  },
  {
    id: 'CAT007',
    name: 'Vision',
    fullName: 'Vision Care',
    hasSpecialties: false,
    hasLabServices: false,
    hasServiceManagement: true,
  },
  {
    id: 'CAT008',
    name: 'Wellness',
    fullName: 'Wellness Programs',
    hasSpecialties: false,
    hasLabServices: false,
    hasServiceManagement: true,
  },
] as const;

export type CategoryId = typeof PREDEFINED_CATEGORIES[number]['id'];
