export const PREDEFINED_CATEGORIES = [
  {
    id: 'CAT001',
    name: 'In-Clinic',
    fullName: 'In-Clinic Consultation',
    hasSpecialties: true,
    hasLabServices: false,
    hasServiceManagement: false,
  },
  {
    id: 'CAT002',
    name: 'Pharmacy',
    fullName: 'Pharmacy',
    hasSpecialties: false,
    hasLabServices: false,
    hasServiceManagement: false,
  },
  {
    id: 'CAT003',
    name: 'Radiology-Cardiology',
    fullName: 'Radiology-Cardiology',
    hasSpecialties: false,
    hasLabServices: true,
    hasServiceManagement: false,
  },
  {
    id: 'CAT004',
    name: 'Pathology(Labs)',
    fullName: 'Pathology(Labs)',
    hasSpecialties: false,
    hasLabServices: true,
    labServiceCategories: ['PATHOLOGY', 'OTHER'],
    hasServiceManagement: false,
  },
  {
    id: 'CAT005',
    name: 'Online',
    fullName: 'Online Consultation',
    hasSpecialties: true,
    hasLabServices: false,
    hasServiceManagement: false,
  },
  {
    id: 'CAT006',
    name: 'Dental',
    fullName: 'Dental Services',
    hasSpecialties: false,
    hasLabServices: false,
    hasServiceManagement: true,
  },
  {
    id: 'CAT007',
    name: 'Vision',
    fullName: 'Vision Care',
    hasSpecialties: false,
    hasLabServices: false,
    hasServiceManagement: true,
  },
  {
    id: 'CAT008',
    name: 'Health Packages',
    fullName: 'Health Packages',
    hasSpecialties: false,
    hasLabServices: false,
    hasServiceManagement: true,
  },
  {
    id: 'CAT009',
    name: 'Vaccines',
    fullName: 'Vaccination Services',
    hasSpecialties: false,
    hasLabServices: false,
    hasServiceManagement: false,
    hasVaccinationServices: true,
  },
] as const;

export type CategoryId = typeof PREDEFINED_CATEGORIES[number]['id'];
