name: Simple Deploy to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          command_timeout: 55m

          script: |
            cd ~/opdwallet
            git pull origin main

            echo "🛠 Restarting containers..."
            docker-compose -f docker-compose.simple.yml down

            echo "♻️ Building containers..."
            docker-compose -f docker-compose.simple.yml build --no-cache

            docker-compose -f docker-compose.simple.yml up -d

            echo "✅ Deployment complete"
            docker ps