name: Test SSH Only

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Test SSH Connection
      run: |
        echo "Testing SSH connection..."

        # Decode SSH key
        echo "${{ secrets.EC2_SSH_KEY_BASE64 }}" | base64 -d > key.pem
        chmod 600 key.pem

        # Show key info (safe)
        echo "Key size: $(wc -c < key.pem) bytes"
        if head -n 1 key.pem | grep -q "BEGIN RSA PRIVATE KEY"; then
          echo "✓ Key format correct"
        else
          echo "✗ Key format incorrect"
          echo "First 30 chars: $(head -c 30 key.pem)"
        fi

        # Test SSH
        echo "Connecting to EC2_HOST: ${{ secrets.EC2_HOST }}"
        ssh -v -o StrictHostKeyChecking=no -o ConnectTimeout=10 -i key.pem ubuntu@${{ secrets.EC2_HOST }} 'echo "SUCCESS: Connected to EC2"' 2>&1 | grep -E "(SUCCESS|Permission denied|Connection refused|timeout)"

        # Cleanup
        rm key.pem